# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: web

on:
  push:
    branches:
      - master
    paths:
    - Tailspin.SpaceGame.Web/*
    - Tailspin.SpaceGame.Web.Tests/*
    - .github/workflows/master_githubptt.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'

    - name: Set up npm
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Run npm install
      run: npm install

    - name: Compile Sass assets
      run: ./node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot
      shell: bash

    - name: Run gulp tasks
      run: gulp
      shell: bash

    - name: Build with dotnet
      run: dotnet build --configuration Release
    
    - name: Build the unit test project
      run: dotnet build Tailspin.SpaceGame.Web.Tests/Tailspin.SpaceGame.Web.Tests.csproj --no-restore --configuration Release
    
    - name: Run the unit test
      run: dotnet test Tailspin.SpaceGame.Web.Tests/Tailspin.SpaceGame.Web.Tests.csproj --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'githubptt'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e46c3f4b18e94fa3ba42a6316458c61a }}
        package: ${{env.DOTNET_ROOT}}/myapp 
